# Generated by Django 4.0.1 on 2022-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(max_length=200),
        ),
    ]
